export const SITE_TITLE = 'Arhella';
export const SITE_DESCRIPTION = 'Welcome to my website!';

export const PROJECTS_DATA = [
  {
    id: 'chimu.moe',
    href: 'https://chimu.moe',
    title: 'chimu.moe',
    text: 'osu! beatmaps mirror for removed maps from official server',
    imageSrc: '/chimu.png',
    color: '#FF6666',
    buttonColor: '#342121',
    buttonTextColor: '#B6B1B1',
  },
  {
    id: 'CircleForms',
    href: 'https://circleforms.net',
    title: 'CircleForms',
    text: 'an alternative to google forms with additional integration with osu! API',
    imageSrc: '/circleforms.png',
    color: '#FF66AA',
    buttonColor: '#352028',
    buttonTextColor: '#B7B1B4',
  },
  {
    id: 'The Potencial',
    href: 'https://www.google.com/',
    title: 'The Potencial',
    text: 'CRM-system for IT companies',
    imageSrc: '/potential.png',
    color: '#FFFFFF',
    buttonColor: '#343535',
    buttonTextColor: '#B7B7B7',
  },
  {
    id: 'ESET NOD32 Antivirus',
    href: 'https://www.google.com/',
    title: 'ESET NOD32 Antivirus',
    text: 'Redesign of ESET NOD32 Antivirus Windows App',
    imageSrc: '/eset.png',
    color: '#0094A1',
    buttonColor: '#142627',
    buttonTextColor: '#AEB3B3',
  },
  {
    id: 'OSIRIS',
    href: 'https://www.google.com/',
    title: 'OSIRIS',
    text: 'CRM-system for a funeral parlour company (test task using design system)',
    imageSrc: '/osiris.png',
    color: '#E0343F',
    buttonColor: '#2D181A',
    buttonTextColor: '#B5AFAF',
  },
  {
    id: 'Readmanga.live',
    href: 'https://readmanga.live',
    title: 'Readmanga.live “last updates and “manga list redesign',
    text: 'the largest database of manga in runet',
    imageSrc: '/readmanga.png',
    color: '#EDD369',
    buttonColor: '#302D20',
    buttonTextColor: '#B6B5B1',
  },
  {
    id: 'Graphic Design',
    href: 'https://www.google.com/',
    title: 'Graphic Design',
    text: 'Some of my works for community tournaments and Yandex Test Task',
    imageSrc: '/graphicdesign.png',
    color: '#FE704B',
    buttonColor: '#301F1A',
    buttonTextColor: '#B7B2B0',
  },
];
